version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3337:3337"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    command: sh -c "sleep 5 && node server.js"
    restart: always

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    image: nginx:alpine
    ports:
      - "3338:3338"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always
volumes:
  postgres_data:
